In [4]:
import pandas as pd
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [8]:
train_df = pd.read_csv(
    r"E:\CodSoft_datasets_for_tasks\archive\Genre Classification Dataset\train_data.txt",
    sep=" ::: ",
    engine="python",
    names=["ID","TITLE","GENRE","DESCRIPTION"]
)
train_df.head()

,ID,TITLE,GENRE,DESCRIPTION
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his doc...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous re...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fiel...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends meet...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-rec...

In [10]:
print(train_df.shape)
print(train_df["GENRE"].nunique())

(54214, 4)
27

In [12]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

train_df["DESCRIPTION"] = train_df["DESCRIPTION"].apply(clean_text)

In [14]:
vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words='english'
)

X = vectorizer.fit_transform(train_df["DESCRIPTION"])

y = train_df["GENRE"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [18]:
predictions = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, predictions))

print(classification_report(y_test, predictions))

Accuracy: 0.5781610255464354
              precision    recall  f1-score   support

      action       0.55      0.24      0.33       263
       adult       0.81      0.20      0.32       112
   adventure       0.46      0.14      0.21       139
   animation       0.60      0.06      0.11       104
   biography       0.00      0.00      0.00        61
      comedy       0.51      0.58      0.54      1443
       crime       0.40      0.02      0.04       107
 documentary       0.66      0.85      0.74      2659
       drama       0.54      0.79      0.64      2697
      family       0.45      0.07      0.12       150
     fantasy       0.00      0.00      0.00        74
   game-show       0.95      0.45      0.61        40
     history       0.00      0.00      0.00        45
      horror       0.66      0.58      0.62       431
       music       0.68      0.47      0.55       144
     musical       1.00      0.02      0.04        50
     mystery       0.00      0.00      0.00        56
        news       1.00      0.03      0.06        34
  reality-tv       0.55      0.15      0.24       192
     romance       0.14      0.01      0.01       151
      sci-fi       0.55      0.20      0.29       143
       short       0.47      0.31      0.37      1045
       sport       0.75      0.23      0.35        93
   talk-show       0.64      0.11      0.19        81
    thriller       0.39      0.12      0.18       309
         war       0.00      0.00      0.00        20
     western       0.97      0.71      0.82       200

    accuracy                           0.58     10843
   macro avg       0.51      0.23      0.27     10843
weighted avg       0.56      0.58      0.53     10843

C:\Users\jainu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\jainu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\jainu\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [20]:
test_df = pd.read_csv(
    r"E:\CodSoft_datasets_for_tasks\archive\Genre Classification Dataset\test_data.txt",
    sep=" ::: ",
    engine="python",
    names=["ID","TITLE","DESCRIPTION"]
)

test_df.head()

,ID,TITLE,DESCRIPTION
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apart..."
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty chi..."
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family o...
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with his..."
4,5,Er nu zhai (1955),Before he was known internationally as a marti...

In [22]:
test_descriptions = test_df["DESCRIPTION"].apply(clean_text)

X_test_real = vectorizer.transform(test_descriptions)

predicted_genres = model.predict(X_test_real)

test_df["PREDICTED_GENRE"] = predicted_genres

test_df.head()

,ID,TITLE,DESCRIPTION,PREDICTED_GENRE
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apart...",drama
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty chi...",drama
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family o...,documentary
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with his...",drama
4,5,Er nu zhai (1955),Before he was known internationally as a marti...,drama

In [24]:
solution_df = pd.read_csv(
    r"E:\CodSoft_datasets_for_tasks\archive\Genre Classification Dataset\test_data_solution.txt",
    sep=" ::: ",
    engine="python",
    names=["ID","TITLE","GENRE","DESCRIPTION"]
)

In [26]:
accuracy = accuracy_score(
    solution_df["GENRE"],
    predicted_genres
)

print("Final Test Accuracy:", accuracy)

Final Test Accuracy: 0.5823616236162361